Repository PaloAltoNetworks/terraform-azurerm-swfw-modules, pull requests merged in 2024-09, with the labels that each got.

#85 feat: Introduce VNET custom DNS servers
  .pre-commit-config.yaml
  examples/common_vmseries/README.md
  examples/common_vmseries/main.tf
  examples/common_vmseries/variables.tf
  examples/common_vmseries_and_autoscale/README.md
  examples/common_vmseries_and_autoscale/main.tf
  examples/common_vmseries_and_autoscale/variables.tf
  examples/dedicated_vmseries/README.md
  examples/dedicated_vmseries/main.tf
  examples/dedicated_vmseries/variables.tf
  examples/dedicated_vmseries_and_autoscale/README.md
  examples/dedicated_vmseries_and_autoscale/main.tf
  examples/dedicated_vmseries_and_autoscale/variables.tf
  examples/gwlb_with_vmseries/README.md
  examples/gwlb_with_vmseries/main.tf
  examples/gwlb_with_vmseries/variables.tf
  examples/standalone_panorama/README.md
  examples/standalone_panorama/main.tf
  examples/standalone_panorama/variables.tf
  examples/standalone_vmseries/README.md
  examples/standalone_vmseries/main.tf
  examples/standalone_vmseries/variables.tf
  modules/vnet/README.md
  modules/vnet/main.tf
  modules/vnet/variables.tf
  tests/appgw/README.md
  tests/appgw/main.tf
  tests/appgw/variables.tf
  tests/virtual_network_gateway/README.md
  tests/virtual_network_gateway/main.tf
  tests/virtual_network_gateway/variables.tf
Labels: enhancement

#89 feat(vmseries): VMSeries appgw backend pool association
  examples/common_vmseries/README.md
  examples/common_vmseries/main.tf
  examples/common_vmseries/variables.tf
  examples/dedicated_vmseries/README.md
  examples/dedicated_vmseries/main.tf
  examples/dedicated_vmseries/variables.tf
  examples/gwlb_with_vmseries/README.md
  examples/gwlb_with_vmseries/main.tf
  examples/gwlb_with_vmseries/variables.tf
  examples/standalone_vmseries/README.md
  examples/standalone_vmseries/main.tf
  examples/standalone_vmseries/variables.tf
  modules/vmseries/README.md
  modules/vmseries/main.tf
  modules/vmseries/variables.tf
Labels: enhancement

#93 fix: Restrict maximum AzureRM provider version for bootstrap module
  modules/bootstrap/README.md
  modules/bootstrap/versions.tf
Labels: bug

#86 feat!: Bump AzureRM to v4 and replace deprecated properties
  examples/common_vmseries/README.md
  examples/common_vmseries/variables.tf
  examples/common_vmseries_and_autoscale/README.md
  examples/common_vmseries_and_autoscale/variables.tf
  examples/dedicated_vmseries/README.md
  examples/dedicated_vmseries/variables.tf
  examples/dedicated_vmseries_and_autoscale/README.md
  examples/dedicated_vmseries_and_autoscale/variables.tf
  examples/gwlb_with_vmseries/README.md
  examples/gwlb_with_vmseries/variables.tf
  examples/standalone_panorama/README.md
  examples/standalone_panorama/variables.tf
  examples/standalone_vmseries/README.md
  examples/standalone_vmseries/variables.tf
  modules/appgw/README.md
  modules/appgw/versions.tf
  modules/bootstrap/README.md
  modules/bootstrap/versions.tf
  modules/gwlb/README.md
  modules/gwlb/versions.tf
  modules/loadbalancer/README.md
  modules/loadbalancer/versions.tf
  modules/natgw/README.md
  modules/natgw/versions.tf
  modules/ngfw_metrics/README.md
  modules/ngfw_metrics/versions.tf
  modules/panorama/README.md
  modules/panorama/main.tf
  modules/panorama/versions.tf
  modules/public_ip/README.md
  modules/public_ip/versions.tf
  modules/test_infrastructure/.README.md
  modules/test_infrastructure/versions.tf
  modules/virtual_machine/main.tf
  modules/virtual_network_gateway/README.md
  modules/virtual_network_gateway/versions.tf
  modules/vmseries/README.md
  modules/vmseries/versions.tf
  modules/vmss/README.md
  modules/vmss/versions.tf
  modules/vnet/README.md
  modules/vnet/main.tf
  modules/vnet/outputs.tf
  modules/vnet/variables.tf
  modules/vnet/versions.tf
  modules/vnet_peering/README.md
  modules/vnet_peering/versions.tf
Labels: enhancement

#94 docs: Documentation bug fixes in README snippets
  modules/appgw/.header.md
  modules/appgw/README.md
  modules/gwlb/.header.md
  modules/gwlb/README.md
  modules/loadbalancer/.header.md
  modules/loadbalancer/README.md
  modules/natgw/.header.md
  modules/natgw/README.md
  modules/virtual_machine/.README.md
  modules/virtual_network_gateway/.header.md
  modules/virtual_network_gateway/README.md
  modules/vmss/.header.md
  modules/vmss/README.md
  modules/vmss/versions.tf
  modules/vnet/.header.md
  modules/vnet/README.md
Labels: documentation
