Repository PaloAltoNetworks/terraform-azurerm-swfw-modules, pull requests merged in 2025-03, with the labels that each got.

#132 fix(bootstrap): Replace file shares IDs with URLs for storage_share_id property
  modules/bootstrap/main.tf
Labels: bug

#113 feat(cloudngfw): Introduce Cloud NGFW module with VNET-based example
  examples/common_cloudngfw/.header.md
  examples/common_cloudngfw/README.md
  examples/common_cloudngfw/example.tfvars
  examples/common_cloudngfw/main.tf
  examples/common_cloudngfw/main_test.go
  examples/common_cloudngfw/outputs.tf
  examples/common_cloudngfw/variables.tf
  examples/common_cloudngfw/versions.tf
  modules/cloudngfw/.header.md
  modules/cloudngfw/README.md
  modules/cloudngfw/main.tf
  modules/cloudngfw/main_test.go
  modules/cloudngfw/outputs.tf
  modules/cloudngfw/variables.tf
  modules/cloudngfw/versions.tf
  modules/vnet/main.tf
Labels: enhancement

#137 docs(vnet): Update usage example of sourcing a subnet in README of the vnet module
  modules/vnet/.header.md
  modules/vnet/README.md
Labels: documentation
